import React, { useState, useEffect } from 'react';
import { counsellorReviewApi } from '../api/counsellorReviewApi';

export default function CounsellorDashboardPage() {
  const [reviews, setReviews] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedReview, setSelectedReview] = useState(null);
  const [feedback, setFeedback] = useState('');
  const [actionLoading, setActionLoading] = useState(false);
  const [alert, setAlert] = useState(null);

  useEffect(() => {
    loadPendingReviews();
  }, []);

  const loadPendingReviews = async () => {
    try {
      setLoading(true);
      const data = await counsellorReviewApi.getPendingReviews();
      setReviews(data);
    } catch {
      setAlert({ type: 'error', text: 'Failed to load pending reviews from server.' });
    } finally {
      setLoading(false);
    }
  };

  const handleDecision = async (decision) => {
    if (!selectedReview) return;
    try {
      setActionLoading(true);
      await counsellorReviewApi.submitDecision(selectedReview.id, decision, feedback);
      setAlert({ type: 'success', text: `Pathway marked as "${decision}" successfully.` });
      setSelectedReview(null);
      setFeedback('');
      loadPendingReviews();
    } catch {
      setAlert({ type: 'error', text: 'Failed to submit counsellor decision.' });
    } finally {
      setActionLoading(false);
    }
  };

  return (
    <div style={{ padding: '2rem', maxWidth: '1200px', margin: '0 auto', fontFamily: 'system-ui, sans-serif' }}>
      <header style={{ marginBottom: '1.5rem', borderBottom: '1px solid #334155', paddingBottom: '1rem' }}>
        <h1 style={{ fontSize: '1.8rem', color: '#f8fafc', margin: 0 }}>Counsellor Pathway Verification Portal</h1>
        <p style={{ color: '#94a3b8', marginTop: '0.25rem' }}>
          Evaluate high-risk flags and review student pathway feasibility generated by Reality Check Agent.
        </p>
      </header>

      {alert && (
        <div style={{
          padding: '0.85rem',
          borderRadius: '6px',
          marginBottom: '1.25rem',
          background: alert.type === 'success' ? '#14532d' : '#7f1d1d',
          color: '#ffffff',
          fontWeight: 500
        }}>
          {alert.text}
        </div>
      )}

      {loading ? (
        <p style={{ color: '#94a3b8' }}>Loading pending reviews...</p>
      ) : reviews.length === 0 ? (
        <div style={{ padding: '2.5rem', background: '#1e293b', borderRadius: '8px', textAlign: 'center', border: '1px solid #334155' }}>
          <h3 style={{ color: '#f8fafc', margin: '0 0 0.5rem 0' }}>No Pending Reviews</h3>
          <p style={{ color: '#94a3b8', margin: 0 }}>All student pathways are currently up to date or approved.</p>
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: selectedReview ? '1.1fr 1.9fr' : '1fr', gap: '1.5rem' }}>
          {/* Pending List */}
          <div>
            <h3 style={{ fontSize: '1.1rem', color: '#f8fafc', marginBottom: '0.75rem' }}>
              Pending Queue ({reviews.length})
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {reviews.map((rev) => (
                <div
                  key={rev.id}
                  onClick={() => setSelectedReview(rev)}
                  style={{
                    padding: '1rem',
                    borderRadius: '8px',
                    border: selectedReview?.id === rev.id ? '2px solid #3b82f6' : '1px solid #334155',
                    background: rev.isHighRisk ? '#450a0a' : '#1e293b',
                    cursor: 'pointer'
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span style={{ fontWeight: 600, color: '#f8fafc' }}>Student ID: {rev.studentId.substring(0, 8)}...</span>
                    {rev.isHighRisk && (
                      <span style={{ background: '#e11d48', color: '#fff', fontSize: '11px', padding: '2px 8px', borderRadius: '12px', fontWeight: 600 }}>
                        High Risk
                      </span>
                    )}
                  </div>
                  <p style={{ fontSize: '13px', color: '#cbd5e1', margin: '0.5rem 0' }}>{rev.feasibilitySummary}</p>
                  <small style={{ color: '#64748b' }}>Created: {new Date(rev.createdAt).toLocaleString()}</small>
                </div>
              ))}
            </div>
          </div>

          {/* Decision Box */}
          {selectedReview && (
            <div style={{ padding: '1.5rem', background: '#1e293b', borderRadius: '8px', border: '1px solid #334155' }}>
              <h3 style={{ marginTop: 0, color: '#f8fafc' }}>Pathway Evaluation Details</h3>
              <p style={{ color: '#cbd5e1' }}><strong>Feasibility Overview:</strong> {selectedReview.feasibilitySummary}</p>
              
              {selectedReview.isHighRisk && (
                <div style={{ padding: '0.75rem', background: '#450a0a', borderLeft: '4px solid #ef4444', borderRadius: '4px', marginBottom: '1rem' }}>
                  <strong style={{ color: '#fca5a5' }}>AI Flagged Risk Factor:</strong>
                  <p style={{ margin: '0.25rem 0 0 0', color: '#fecaca', fontSize: '14px' }}>{selectedReview.riskReason}</p>
                </div>
              )}

              <div style={{ marginTop: '1.5rem' }}>
                <label style={{ display: 'block', fontWeight: 600, color: '#cbd5e1', marginBottom: '0.5rem' }}>
                  Counsellor Recommendation / Notes:
                </label>
                <textarea
                  rows="4"
                  value={feedback}
                  onChange={(e) => setFeedback(e.target.value)}
                  placeholder="State requirements, remedial course steps, or reason for revision..."
                  style={{ width: '100%', padding: '0.75rem', borderRadius: '6px', border: '1px solid #475569', background: '#0f172a', color: '#f8fafc', boxSizing: 'border-box', marginBottom: '1rem' }}
                />

                <div style={{ display: 'flex', gap: '0.75rem' }}>
                  <button
                    disabled={actionLoading}
                    onClick={() => handleDecision('Approved')}
                    style={{ flex: 1, padding: '0.75rem', background: '#16a34a', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 600 }}
                  >
                    Approve
                  </button>
                  <button
                    disabled={actionLoading}
                    onClick={() => handleDecision('NeedsRevision')}
                    style={{ flex: 1, padding: '0.75rem', background: '#d97706', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 600 }}
                  >
                    Revision
                  </button>
                  <button
                    disabled={actionLoading}
                    onClick={() => handleDecision('Rejected')}
                    style={{ flex: 1, padding: '0.75rem', background: '#dc2626', color: '#fff', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 600 }}
                  >
                    Reject
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}